### ISSUE TITLE
Insufficient memory issues tons of errors

### ISSUE THREAD

**Issue by Kiaos** [ModOrganizer/modorganizer#1]
Here is are my logs for Mod orgainizer 2.0.8.3 Revision: c64e12a

[logs.zip](https://github.com/ModOrganizer/modorganizer/files/1316510/logs.zip)

**Comment by Kiaos** [comment]
my dumb
[ModOrganizer.exe.dmp.zip](https://github.com/ModOrganizer/modorganizer/files/1316519/ModOrganizer.exe.dmp.zip)

**Comment by Kiaos** [comment]
Mod orgainizer logs 
[logs.zip](https://github.com/ModOrganizer/modorganizer/files/1316525/logs.zip)

**Comment by iaz3** [comment]
Relevant:

https://github.com/LePresidente/modorganizer/issues/45
https://github.com/LePresidente/modorganizer/issues/80
https://github.com/LePresidente/modorganizer/issues/50

**Comment by VernMcC** [comment]
One of the things that helped my memory issues was to have MO2 launch cmd.exe and then run f4se_loader.exe from the command line.  That has kept the handles balloon from taking up my resources.

**Comment by Silarn** [comment]
This has been fixed on LePresidente's fork - which is the working fork until the refactoring is complete.

**Comment by iaz3** [comment]
Good to know, thanks.

Fixed upstream.
